version: '3.9'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker/data-rabbitmq:/var/lib/rabbitmq/
    environment:
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=admin
      - RMQ_PASSWORD=admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
    restart: always
    networks:
      - localnet
  db-postgres:
    container_name: db-postgres
    restart: always
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=db-postgres
      - POSTGRES_DB=assembly-voter-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    networks:
      - localnet
  assembly-voter:
    container_name: assembly-voter
    build: .
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db-postgres
      - POSTGRES_DB=assembly-voter-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=admin
      - RMQ_PASSWORD=admin
      - ENV_PROFILE=prod
    networks:
      - localnet
    restart: on-failure
networks:
  localnet:
    driver: bridge