version: '3'

services:

  db-postgres:
    container_name: db-postgres
    restart: always
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: assembly-voter-db
      POSTGRES_PASSWORD: 123
